packages:
  - "apps/*"
  - "packages/*"
  - "features/*"
  - "widgets/*"
  - "integrations/*"
  - "plugins/*"

catalog:
  "@types/node": "^25.5.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  lucide-react: "^0.577.0"
  motion: "^12.38.0"
  nuqs: "^2.8.9"
  react: "^19.2.4"
  react-dom: "^19.2.4"
  swr: "^2.4.1"
  typescript: "^5.9.3"
  vitest: "^4.1.0"
  zod: "^4.3.6"
