export const VIEW_STATE_QUERY_KEYS = {
  advancedSection: "advancedSection",
  ai: "ai",
  aiSkillEditor: "aiSkillEditor",
  appearanceSection: "appearanceSection",
  chat: "chat",
  detail: "detail",
  integrationCategory: "integrationCategory",
  integrationIntent: "integrationIntent",
  integrationTab: "integrationTab",
  launcher: "launcher",
  layout: "layout",
  layoutDialog: "layoutDialog",
  notificationsTab: "notificationsTab",
  plugin: "plugin",
  project: "project",
  projectDialog: "projectDialog",
  service: "service",
  settings: "settings",
  settingsInstaller: "settingsInstaller",
  settingsPlugin: "settingsPlugin",
  settingsPluginTab: "settingsPluginTab",
  settingsRelay: "settingsRelay",
  setup: "setup",
  shortcutScope: "shortcutScope",
  widgetCategory: "widgetCategory",
  widgetConfig: "widget-config",
} as const;

export type ViewStateQueryKey = (typeof VIEW_STATE_QUERY_KEYS)[keyof typeof VIEW_STATE_QUERY_KEYS];
