import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import process from "node:process";

type BumpType = "major" | "minor" | "patch";

type ChangesetEntry = {
  filePath: string;
  summary: string;
  packages: string[];
  contributor: string | null;
};

type SectionName = "What's new" | "Fixes" | "Desktop" | "Builders" | "Upgrade notes";

const rootDir = process.cwd();
const desktopPackagePath = path.join(rootDir, "apps", "desktop", "package.json");
const desktopNextPath = path.join(rootDir, "release-notes", "desktop-next.md");
const summaryStartMarker = "<!-- radarboard-release-notes:summary:start -->";
const summaryEndMarker = "<!-- radarboard-release-notes:summary:end -->";
const autoStartMarker = "<!-- radarboard-release-notes:auto-generated:start -->";
const autoEndMarker = "<!-- radarboard-release-notes:auto-generated:end -->";

function runGit(args: string[]): string {
  return execFileSync("git", args, {
    cwd: rootDir,
    encoding: "utf8",
    stdio: ["inherit", "pipe", "inherit"],
  }).trim();
}

function parseArg(flag: string): string | null {
  const index = process.argv.indexOf(flag);
  if (index === -1) return null;
  return process.argv[index + 1] ?? null;
}

function readDesktopVersion(): string {
  const packageJson = JSON.parse(readFileSync(desktopPackagePath, "utf8")) as { version?: string };
  if (!packageJson.version) {
    throw new Error(`Missing version in ${desktopPackagePath}`);
  }
  return packageJson.version;
}

function defaultTagName(): string {
  return `desktop-v${readDesktopVersion()}`;
}

function parseChangesetMarkdown(markdown: string): { packages: string[]; summary: string } {
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/m.exec(markdown);

  if (!match) {
    throw new Error("Invalid changeset markdown format");
  }

  const frontmatter = match[1];
  const body = match[2].trim();
  const packages = frontmatter
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => /^"([^"]+)":\s*(major|minor|patch)$/.exec(line))
    .filter((value): value is RegExpExecArray => Boolean(value))
    .map((value) => value[1]);

  return {
    packages,
    summary: body.replace(/\s+/g, " ").trim(),
  };
}

function inferContributor(filePath: string): string | null {
  const raw = runGit(["log", "-1", "--format=%an|%ae", "--", filePath]);

  if (!raw) return null;

  const [name, email] = raw.split("|");
  if (!name) return null;

  const noreplyMatch = /(?:\d+\+)?([^@]+)@users\.noreply\.github\.com$/i.exec(email ?? "");
  if (noreplyMatch?.[1]) {
    return `@${noreplyMatch[1]}`;
  }

  return name;
}

function classifySection(summary: string, packages: string[]): SectionName {
  const lowerSummary = summary.toLowerCase();
  const builderPackage = packages.some((pkg) =>
    ["plugin", "integration", "widget", "sdk", "types"].some((keyword) => pkg.includes(keyword))
  );

  if (
    ["breaking", "migrate", "migration", "rename", "deprecated", "require", "drop support"].some((keyword) =>
      lowerSummary.includes(keyword)
    )
  ) {
    return "Upgrade notes";
  }

  if (["desktop", "macos", "tauri", "updater", "dmg"].some((keyword) => lowerSummary.includes(keyword))) {
    return "Desktop";
  }

  if (
    ["fix", "fixed", "prevent", "restore", "correct", "stabilize", "avoid", "ensure", "repair"].some((keyword) =>
      lowerSummary.includes(keyword)
    )
  ) {
    return "Fixes";
  }

  if (builderPackage || ["api", "sdk", "hook", "schema", "mcp", "route"].some((keyword) => lowerSummary.includes(keyword))) {
    return "Builders";
  }

  return "What's new";
}

function collectConsumedChangesets(): ChangesetEntry[] {
  const diffOutput = runGit(["diff", "--name-status", "--", ".changeset"]);
  const deletedFiles = diffOutput
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => line.split("\t"))
    .filter(([status, filePath]) => status === "D" && filePath.endsWith(".md") && filePath !== ".changeset/README.md")
    .map(([, filePath]) => filePath);

  return deletedFiles.map((filePath) => {
    const markdown = runGit(["show", `HEAD:${filePath}`]);
    const parsed = parseChangesetMarkdown(markdown);

    return {
      filePath,
      summary: parsed.summary,
      packages: parsed.packages,
      contributor: inferContributor(filePath),
    };
  });
}

function formatEntry(entry: ChangesetEntry): string {
  if (entry.contributor) {
    return `- ${entry.summary}. Thanks ${entry.contributor}.`;
  }

  return `- ${entry.summary}.`;
}

function buildAutoGeneratedBlock(entries: ChangesetEntry[]): string {
  const sections = new Map<SectionName, string[]>();

  for (const entry of entries) {
    const section = classifySection(entry.summary, entry.packages);
    const existing = sections.get(section) ?? [];
    existing.push(formatEntry(entry));
    sections.set(section, existing);
  }

  const orderedSections: SectionName[] = ["What's new", "Fixes", "Desktop", "Builders", "Upgrade notes"];
  const sectionLines: string[] = [autoStartMarker];

  for (const section of orderedSections) {
    const lines = sections.get(section);
    if (!lines || lines.length === 0) continue;

    sectionLines.push(`## ${section}`, "");
    sectionLines.push(...lines, "");
  }

  const contributors = Array.from(new Set(entries.map((entry) => entry.contributor).filter(Boolean))) as string[];
  if (contributors.length > 0) {
    sectionLines.push("## Thanks", "");
    sectionLines.push(`- Thanks ${contributors.join(", ")} for contributing to this release.`, "");
  }

  sectionLines.push(autoEndMarker);
  return sectionLines.join("\n").trim();
}

function extractPreservedSummary(existingContents: string | null): string {
  const nextDraft = existsSync(desktopNextPath) ? readFileSync(desktopNextPath, "utf8").trim() : null;

  if (nextDraft) {
    return [summaryStartMarker, nextDraft, summaryEndMarker].join("\n");
  }

  if (!existingContents) {
    return [
      summaryStartMarker,
      "<!-- Optional: add a short curated intro above the generated notes if you want one. -->",
      summaryEndMarker,
    ].join("\n");
  }

  const startIndex = existingContents.indexOf(summaryStartMarker);
  const endIndex = existingContents.indexOf(summaryEndMarker);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return [
      summaryStartMarker,
      "<!-- Optional: add a short curated intro above the generated notes if you want one. -->",
      summaryEndMarker,
    ].join("\n");
  }

  return existingContents.slice(startIndex, endIndex + summaryEndMarker.length).trim();
}

function main() {
  const tagName = parseArg("--tag") ?? defaultTagName();
  const targetPath = path.join(rootDir, "release-notes", `${tagName}.md`);
  const entries = collectConsumedChangesets();

  if (entries.length === 0) {
    throw new Error("No consumed changesets found in git diff; generate release notes after changeset version runs");
  }

  const existingContents = existsSync(targetPath) ? readFileSync(targetPath, "utf8") : null;
  const summaryBlock = extractPreservedSummary(existingContents);
  const autoBlock = buildAutoGeneratedBlock(entries);
  const output = [`# Radarboard Desktop ${tagName}`, "", summaryBlock, "", autoBlock, ""].join("\n");

  writeFileSync(targetPath, output);
  console.log(`generated release notes: ${path.relative(rootDir, targetPath)}`);
}

main();
