#!/usr/bin/env tsx
/**
 * Generate Markdown documentation from Zod schemas used in API routes.
 *
 * Usage:
 *   pnpm tsx scripts/generate-schema-docs.ts          # generate docs
 *   pnpm tsx scripts/generate-schema-docs.ts --check   # check for drift
 *
 * Scans API route files for exported Zod schemas, extracts their shape,
 * and writes Markdown docs to docs/schemas/. In --check mode, compares
 * generated output to committed docs and exits non-zero on drift.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const API_DIR = join(ROOT, "apps/app/app/api");
const OUTPUT_DIR = join(ROOT, "docs/schemas");
const CHECK_MODE = process.argv.includes("--check");

interface SchemaEntry {
  file: string;
  name: string;
  fields: string[];
}

/**
 * Extract Zod schema definitions from a TypeScript file.
 * Looks for patterns like: `const FooSchema = z.object({...})`
 */
function extractSchemas(filePath: string): SchemaEntry[] {
  const content = readFileSync(filePath, "utf-8");
  const entries: SchemaEntry[] = [];

  // Match: const/let XxxSchema = z.object({...})
  const schemaRegex = /(?:const|let)\s+(\w+Schema)\s*=\s*z\.object\(\{([^}]*(?:\{[^}]*\}[^}]*)*)\}\)/g;
  let match: RegExpExecArray | null;

  while ((match = schemaRegex.exec(content)) !== null) {
    const name = match[1]!;
    const body = match[2]!;

    // Extract field names and their types from the body
    const fieldRegex = /(\w+)\s*:\s*z\.(\w+)/g;
    const fields: string[] = [];
    let fieldMatch: RegExpExecArray | null;

    while ((fieldMatch = fieldRegex.exec(body)) !== null) {
      fields.push(`${fieldMatch[1]}: z.${fieldMatch[2]}()`);
    }

    entries.push({
      file: relative(ROOT, filePath),
      name,
      fields,
    });
  }

  return entries;
}

/** Recursively find all .ts files in a directory. */
function findTsFiles(dir: string): string[] {
  const files: string[] = [];
  if (!existsSync(dir)) return files;

  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      files.push(...findTsFiles(full));
    } else if (entry.endsWith(".ts") && !entry.endsWith(".test.ts")) {
      files.push(full);
    }
  }
  return files;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const apiFiles = findTsFiles(API_DIR);
const allSchemas: SchemaEntry[] = [];

for (const file of apiFiles) {
  allSchemas.push(...extractSchemas(file));
}

// Also scan key lib files
const libFiles = [
  join(ROOT, "apps/app/lib/env.ts"),
  join(ROOT, "apps/app/lib/radarboard-config.ts"),
];

for (const file of libFiles) {
  if (existsSync(file)) {
    allSchemas.push(...extractSchemas(file));
  }
}

// Group by file
const byFile = new Map<string, SchemaEntry[]>();
for (const entry of allSchemas) {
  const group = byFile.get(entry.file) ?? [];
  group.push(entry);
  byFile.set(entry.file, group);
}

// Generate Markdown
const lines: string[] = [
  "# API Schema Reference",
  "",
  "> Auto-generated by `scripts/generate-schema-docs.ts`. Do not edit manually.",
  "",
  `Generated: ${new Date().toISOString().split("T")[0]}`,
  "",
  `Total schemas: ${allSchemas.length}`,
  "",
  "---",
  "",
];

for (const [file, schemas] of [...byFile.entries()].sort()) {
  lines.push(`## \`${file}\``);
  lines.push("");

  for (const schema of schemas) {
    lines.push(`### ${schema.name}`);
    lines.push("");
    if (schema.fields.length > 0) {
      lines.push("```typescript");
      for (const field of schema.fields) {
        lines.push(`  ${field}`);
      }
      lines.push("```");
    } else {
      lines.push("*No extractable fields*");
    }
    lines.push("");
  }
}

const content = lines.join("\n");

if (CHECK_MODE) {
  const existingPath = join(OUTPUT_DIR, "api-schemas.md");
  if (!existsSync(existingPath)) {
    console.error("Schema docs not found. Run `pnpm tsx scripts/generate-schema-docs.ts` first.");
    process.exit(1);
  }

  const existing = readFileSync(existingPath, "utf-8");

  // Compare content hashes (ignoring the date line)
  const stripDate = (s: string) => s.replace(/Generated: \d{4}-\d{2}-\d{2}/, "Generated: DATE");
  const hashA = createHash("sha256").update(stripDate(existing)).digest("hex");
  const hashB = createHash("sha256").update(stripDate(content)).digest("hex");

  if (hashA !== hashB) {
    console.error("Schema drift detected! Run `pnpm tsx scripts/generate-schema-docs.ts` to update.");
    process.exit(1);
  }

  console.log("Schema docs are up to date.");
  process.exit(0);
}

// Write output
if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

writeFileSync(join(OUTPUT_DIR, "api-schemas.md"), content, "utf-8");
console.log(`Written ${allSchemas.length} schemas to docs/schemas/api-schemas.md`);
