/**
 * __PLUGIN_NAME__ — Data types
 *
 * Define your plugin's domain types here. These are used by the overlay
 * component, MCP tools, and the plugin's DB storage.
 */

/**
 * A single item managed by this plugin.
 *
 * Works with `createCrudHelper<__PLUGIN_PASCAL__Item>(api, "item")`.
 * The `id` and `createdAt` fields are auto-generated by the CRUD helper.
 */
export interface __PLUGIN_PASCAL__Item {
  /** Unique identifier (UUID). Auto-generated by CRUD helper. */
  id: string;
  /** Display title. */
  title: string;
  /** Whether the item is completed. */
  completed: boolean;
  /** Unix timestamp (ms). Auto-generated by CRUD helper on create. */
  createdAt: number;
}
